"""empty message

Revision ID: 13942816381c
Revises: b301771a4cef
Create Date: 2022-12-25 22:29:36.890174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13942816381c'
down_revision = 'b301771a4cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('user', 
            sa.Column( 'date', sa.DateTime(), nullable=True)
        )                                    
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date')

    # ### end Alembic commands ###
